# Generated by Django 3.0.3 on 2020-03-02 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customer_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='profile',
            new_name='profile_pic',
        ),
    ]
